# Generated by Django 4.2.1 on 2023-06-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0008_series_picture'),
        ('catalog', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to='spravochniki.author'),
            preserve_default=False,
        ),
    ]
