# Generated by Django 4.2.1 on 2023-06-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0008_series_picture'),
        ('catalog', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='zhanr',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, to='spravochniki.zhanr'),
            preserve_default=False,
        ),
    ]
