# Generated by Django 4.2.1 on 2023-06-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0012_remove_series_picture'),
        ('catalog', '0004_book_zhanr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.author'),
        ),
    ]
