# Generated by Django 4.2.1 on 2023-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(default='-', max_length=50, verbose_name='Binding book'),
            preserve_default=False,
        ),
    ]
