# Generated by Django 4.2.1 on 2023-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_book_age_restrictions_alter_book_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(default='2', max_length=50, verbose_name='Format book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='kolvo_book',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=6, verbose_name='Number of books avialable'),
            preserve_default=False,
        ),
    ]
