# Generated by Django 4.2.1 on 2023-06-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_book_active_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Binding book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Format book'),
        ),
    ]
