# Generated by Django 4.2.1 on 2023-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_book_binding_alter_book_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active_book',
            field=models.CharField(choices=[('Y', 'active'), ('N', 'no_active')], max_length=6, verbose_name='Available for order'),
        ),
        migrations.AlterField(
            model_name='book',
            name='kolvo_book',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Number of books available'),
        ),
    ]
