# Generated by Django 4.2.1 on 2023-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_book_active_book_alter_book_kolvo_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='active_book',
            field=models.CharField(choices=[('Active', 'Yes'), ('Not_active', 'No')], max_length=10, verbose_name='Available for order'),
        ),
    ]
