# Generated by Django 4.2.1 on 2023-06-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_book_active_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_entry_catalog',
            field=models.DateField(blank=True, null=True, verbose_name='Date of entry into the catalog'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_of_change',
            field=models.DateField(blank=True, null=True, verbose_name='Date of the last change of the card'),
        ),
    ]
