# Generated by Django 4.2.1 on 2023-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_book_date_entry_catalog_book_date_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price book'),
        ),
    ]
