# Generated by Django 4.2.1 on 2023-06-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0013_status'),
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='spravochniki.status', verbose_name='Order status'),
            preserve_default=False,
        ),
    ]
