# Generated by Django 4.2.1 on 2023-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0003_zhanr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name series book')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description series book')),
            ],
        ),
    ]
