# Generated by Django 4.2.1 on 2023-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0005_author_picture_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='izdatelstvo',
            name='picture',
            field=models.ImageField(default='-', upload_to='uploads/%Y/%m/%d/', verbose_name='Izdatelstvo picture'),
            preserve_default=False,
        ),
    ]
