# Generated by Django 4.2.1 on 2023-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0006_izdatelstvo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhanr',
            name='picture',
            field=models.ImageField(default='-', upload_to='uploads/%Y/%m/%d/', verbose_name='Zhanr picture'),
            preserve_default=False,
        ),
    ]
