# Generated by Django 4.2.1 on 2023-06-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0008_series_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='picture',
        ),
    ]
