# Generated by Django 4.2.1 on 2023-06-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0010_remove_izdatelstvo_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhanr',
            name='picture',
        ),
    ]
